### ISSUE TITLE
Key Error: "gene novelty"

### ISSUE THREAD

**Issue by asipal** [mortazavilab/TALON#110]
Hey, when I try to run talon_abundance I keep getting this error:

> `talon_abundance` --db talon_AF9KO_r2.db.db -a annotation_mm10 --build mm10 --o AF9KO_abundance
Warning: Could not locate novelty type for gene 40427
Warning: Could not locate novelty type for transcript 108132
Traceback (most recent call last):
  File "/home/ia1014/anaconda3/bin/talon_abundance", line 8, in <module>
    sys.exit(main())
  File "/home/ia1014/anaconda3/lib/python3.9/site-packages/talon/post/create_abundance_file_from_database.py", line 469, in main
    write_abundance_file(abundances, colnames, prefix, n_places, datasets, novelty_type, transcript_lengths, outfile)
  File "/home/ia1014/anaconda3/lib/python3.9/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in write_abundance_file
    [ curr_novelty[x] for x in novelty_type_cols] + \
  File "/home/ia1014/anaconda3/lib/python3.9/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in <listcomp>
    [ curr_novelty[x] for x in novelty_type_cols] + \
KeyError: `'gene_novelty'

Even though it gives an error, it also generates an "abundance.tsv" file 356,0 kB in size. I am concerned if this output is complete or it is not complete because it stops generating the output when it runs into an error. I think like this because when I look at the output I can see that the last element in the list is the one before it gives the error for ( Error is caused because tool could not locate novelty type for gene 40427, and in the list the last gene identified has a gene ID 40383). I looked up for this error but couldn't find anything. Thanks for your help in advance!

**Comment by fairliereese** [comment]
Hmmm, it seems like TALON might not have exited correctly when you ran it. Do you have a log file from your actual TALON run? Could you check it for errors or warnings that might indicate that something went wrong?
