### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by adbeggs** [mortazavilab/TALON#134]
Hi,

Have installed latest version of TALON via conda and get this:

```
talon --f talonsamplesheet.txt --db GRCh38.db --build GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta --threads 12
[ 2023-08-07 11:46:26 ] Started TALON run
Traceback (most recent call last):
  File "/rds/homes/b/beggsa/beggsa-clinicalnanopore/software/condaenvs/talon/bin/talon", line 10, in <module>
    sys.exit(main())
  File "/rds/homes/b/beggsa/beggsa-clinicalnanopore/software/condaenvs/talon/lib/python3.7/site-packages/talon/talon.py", line 2417, in main
    run_info.outfiles = init_outfiles(options.outprefix)
  File "/rds/homes/b/beggsa/beggsa-clinicalnanopore/software/condaenvs/talon/lib/python3.7/site-packages/talon/talon.py", line 1485, in init_outfiles
    if os.path.isdir(outprefix):
  File "/rds/homes/b/beggsa/beggsa-clinicalnanopore/software/condaenvs/talon/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by fairliereese** [comment]
Hi, 
Looks like you didn't provide a `--o` argument, which is required to run TALON.
