### ISSUE TITLE
Issue with "Could not retrieve index file"

### ISSUE THREAD

**Issue by patchthr33** [mortazavilab/TALON#136]
When running talon with the example data I received the following errors, is this a known issue?

(py3.10) patrickmacknight@MacBook-Pro example % talon \
       --f config.csv \
       --db example_talon.db \
       --build SIRV --o example
[ 2023-09-27 01:12:14 ] Started TALON run
[ 2023-09-27 01:12:15 ] Merged input SAM/BAM files
[ 2023-09-27 01:12:15 ] Split reads into 7 intervals
[ 2023-09-27 01:12:16 ] Launching parallel annotation jobs
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV1:1000-11644...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV1_1000_11644.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV2:999-5911...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV2_999_5911.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV3:998-9943...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV3_998_9943.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV4:1000-15123...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV4_1000_15123.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV5:1001-13607...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV5_1001_13607.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV6:1000-11839...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV6_1000_11839.bam'
[ 2023-09-27 01:12:16 ] Annotating reads in interval SIRV7:1000-147958...
[E::idx_find_and_load] Could not retrieve index file for 'talon_tmp/interval_files/SIRV7_1000_147958.bam'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/site-packages/talon/talon.py", line 2137, in parallel_talon
    unpack_observed(annotation_info, queue,
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/site-packages/talon/talon.py", line 2335, in unpack_observed
    obs_ID = observed_counter.increment()
NameError: name 'observed_counter' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/bin/talon", line 10, in <module>
    sys.exit(main())
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/site-packages/talon/talon.py", line 2451, in main
    pool.starmap(parallel_talon, jobs)
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/patrickmacknight/opt/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'observed_counter' is not defined

**Comment by fairliereese** [comment]
Check out my answer to #137 here: https://github.com/mortazavilab/TALON/issues/137#issuecomment-1758290250

I'm hoping this solves the issue.

**Comment by fairliereese** [comment]
I tested this behavior and found that I was able to reproduce your issue with Python >= 3.8, as the Stackoverflow thread I found suggested. I have now included <3.8 as a Python dependency in the installation requirements in the latest [release](https://github.com/mortazavilab/TALON/releases/tag/v6.0). Please try installing with this version and see if this fixes your issue!
