### ISSUE TITLE
Issue with talon filter

### ISSUE THREAD

**Issue by rugilemat** [mortazavilab/TALON#142]
Hi,

I have been trying to run talon filter on my database:

```talon_filter_transcripts --db talon/database.db -a Hg38 --maxFracA 0.5 --minCount 1 --minDatasets 3 --o talon/talon_run.csv```

And I'm getting an import error:

```
Traceback (most recent call last):
  File "/users/k19022845/.local/bin/talon_filter_transcripts", line 5, in <module>
    from talon.post.filter_talon_transcripts import main
  File "/users/k19022845/.local/lib/python3.8/site-packages/talon/post/filter_talon_transcripts.py", line 13, in <module>
    from . import ab_utils as autils
  File "/users/k19022845/.local/lib/python3.8/site-packages/talon/post/ab_utils.py", line 6, in <module>
    import scanpy
  File "/users/k19022845/.local/lib/python3.8/site-packages/scanpy/__init__.py", line 17, in <module>
    from . import datasets, logging, queries, external, get, metrics, experimental
  File "/users/k19022845/.local/lib/python3.8/site-packages/scanpy/external/__init__.py", line 4, in <module>
    from . import exporting
  File "/users/k19022845/.local/lib/python3.8/site-packages/scanpy/external/exporting.py", line 14, in <module>
    from pandas.api.types import is_categorical
ImportError: cannot import name 'is_categorical' from 'pandas.api.types' (/users/k19022845/.local/lib/python3.8/site-packages/pandas/api/types/__init__.py)
```

I previously had issues with `numpy`, so I installed it to be version `1.22.4`.

**Comment by fairliereese** [comment]
Just for clarity's sake, did downgrading numpy like this solve your issue? If so I can work it into a new requirements update.

**Comment by rugilemat** [comment]
Hi, no I'm still trying to work this out.

**Comment by fairliereese** [comment]
Can you please check which version of pandas you're running? It looks like the `is_categorical` function has been deprecated. https://stackoverflow.com/questions/76234312/importerror-cannot-import-name-is-categorical-from-pandas-api-types'

**Comment by rugilemat** [comment]
Hi, I'm sorry it took me so long to get back to you. I had some conflicts with conda environment I was initially trying to run it with. However, it now runs fine and having `numpy=1.22.4` solved the issue on my end.
