### ISSUE TITLE
'check_database_integrity' error

### ISSUE THREAD

**Issue by hdm-23** [mortazavilab/TALON#145]
Hi all,

TALON is failing for me at the 'check_database_integrity' step, after completing annotation for all reads in my input. Is there any chance material from the run can be salvaged?
Relevant standard error is pasted below and usage below that:

```
[ 2023-12-23 21:06:32 ] : INFO : [talon.py:2811:parallel_talon] : Annotating reads in interval chr3:99806-198235164...
[ 2023-12-24 15:38:06 ] : INFO : [talon.py:3226:main] : All jobs complete. Starting database update
[ 2023-12-24 15:58:23 ] : INFO : [talon.py:2762:check_database_integrity] : Validating database
[ 2023-12-24 15:58:23 ] : ERROR : [talon.py:2787:check_database_integrity] : Database counter for 'genes' does not match the number of entries in the table. Discarding changes to database and exiting...
[ 2023-12-24 15:58:23 ] : ERROR : [talon.py:2787:check_database_integrity] : Database counter for 'transcripts' does not match the number of entries in the table. Discarding changes to database and exiting...
[ 2023-12-24 15:58:23 ] : ERROR : [talon.py:2787:check_database_integrity] : Database counter for 'location' does not match the number of entries in the table. Discarding changes to database and exiting...
[ 2023-12-24 15:58:24 ] : ERROR : [talon.py:2787:check_database_integrity] : Database counter for 'edge' does not match the number of entries in the table. Discarding changes to database and exiting...
[ 2023-12-24 15:58:26 ] : ERROR : [talon.py:2787:check_database_integrity] : Database counter for 'observed' does not match the number of entries in the table. Discarding changes to database and exiting...
[ 2023-12-24 15:58:26 ] : ERROR : [talon.py:2794:check_database_integrity] : Discrepancy found in database. Discarding changes to database and exiting...
Traceback (most recent call last):
  File "/home/mhale/.conda/envs/python37/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/home/mhale/.conda/envs/python37/lib/python3.7/site-packages/talon/talon.py", line 3230, in main
    update_database(database, batch_size, run_info.outfiles, dataset_db_entries)
  File "/home/mhale/.conda/envs/python37/lib/python3.7/site-packages/talon/talon.py", line 2426, in update_database
    check_database_integrity(cursor)
  File "/home/mhale/.conda/envs/python37/lib/python3.7/site-packages/talon/talon.py", line 2795, in check_database_integrity
    raise RuntimeError(msg)
RuntimeError: Discrepancy found in database. Discarding changes to database and exiting...
```

Usage:

label_reads and initialize_database
```
~/.conda/envs/python37/bin/talon_label_reads --t=8 --f=XYRWR_hifi_Run7_TC_clean_head.sam --g=genome.fa --o=XYRWR_hifi_Run7_TC_Talon_clean # Clean-up step for Talon
~/.conda/envs/python37/bin/talon_initialize_database --f genes.gtf --g Composite --a composite_genes --o Talon_reference

```

Annotate is being submitted as a slurm job 

```
#!/bin/bash -e
#SBATCH -p hgs
#SBATCH -J MAS_ISO_Seq_Run7_Talon_2
#SBATCH -c 8
#SBATCH --mem 200G
#SBATCH -o /home/stdout/Run7_Talon_2-%j.out
#SBATCH -e /home/stdout/Run7_Talon_2-%j.err

cd /home/MAS_Iso_Seq/Talon_Run6_7
~/.conda/envs/python37/bin/talon --threads 8 --f talon_config --db Talon_reference.db --build Composite --o XYRWR_hifi_Run7_Talon_annotate #actual annotate run

```

Thanks!

EDIT: since submission, I've tested the above usage again using a downsampled input sam with the same pre-processing steps and database initialization. With a smaller input file, check_database_integrity works to completion despite the initial database being made from the same gtf annotation file.

**Comment by fairliereese** [comment]
Hi, glad you managed to find a workaround. In all honesty, when I've gotten the database integrity error you mention above, I am almost always able to get it to work by just running the same code again. And in line with what you've mentioned regarding its behavior on a subsampled file, I've found that it's best to chunk talon runs up in batches so that you can give yourself reasonable stopping points so that when you randomly _do_ get the database integrity error, you have a TALON database with data already in it that you can work from so you don't have to start from scratch.

**Comment by hdm-23** [comment]
Thanks for getting back to me @fairliereese. Will implement a 'chunk' approach in the future.

**Comment by fairliereese** [comment]
Just remember if you're to "chunk" it up, I recommend making a backup copy
of the database you're modifying as TALON performs inplace file changes!
