### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by wdg118** [mortazavilab/TALON#149]
Hi @fairliereese , 

I'm trying to initialize the database with:

```
jupyter@0fcbf0476930:~$ talon_initialize_database \
> --f /home/jupyter/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
> --g /home/jupyter/annotations/gencode.v38.primary_assembly.annotation.gtf \
> --a GRCh38 \
> --o talon_database

```

But the I get:

```
Traceback (most recent call last):
  File "/home/jupyter/.local/bin/talon_initialize_database", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter/.local/lib/python3.7/site-packages/talon/initialize_talon_database.py", line 1063, in main
    genes, transcripts, exons = read_gtf_file(gtf_file)
  File "/home/jupyter/.local/lib/python3.7/site-packages/talon/initialize_talon_database.py", line 526, in read_gtf_file
    entry_type = tab_fields[2]
IndexError: list index out of range
jupyter@0fcbf0476930:~$

```

The gtf file seems correct and I don't know whats going on. Help on this would be greatly appreciated!

Thanks<

wdg118

**Comment by fairliereese** [comment]
You've supplied the file names to the wrong arguments. Your GTF needs to be given as the argument for `--f`.

**Comment by wdg118** [comment]
Oh right, sorry! Thanks for picking it up, I'm new to all this!
