### ISSUE TITLE
ValueError: SAM/BAM file 'sam_file' does not exist!

### ISSUE THREAD

**Issue by handesome** [mortazavilab/TALON#156]
Hi！when i run the code
`talon \
--db talon.db \
--f talon_config.csv \
--threads 10 \
--build ini_talon_hg38 \
--cov 0.99 \
--identity 0.95 \
--o /data/work/temp/talon_anno`,the error says
`SAM/BAM file 'sam_file' does not exist!
Traceback (most recent call last):
  File "/usr/local/envs/talon_env/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/envs/talon_env/lib/python3.7/site-packages/talon/talon.py", line 3148, in main
    sam_files, dset_metadata = check_inputs(options)
  File "/usr/local/envs/talon_env/lib/python3.7/site-packages/talon/talon.py", line 1896, in check_inputs
    raise ValueError(msg)
ValueError: SAM/BAM file 'sam_file' does not exist!"
`,what issue could trigger the error?could anyone give some advice?Thanks!

**Comment by KMbio43** [comment]
talon_config.csv contains your sam file, you need to check if your sam file path is correct.

**Comment by handesome** [comment]
> talon_config.csv contains your sam file, you need to check if your sam file path is correct.

Thank you for quick reply! I will check again!
