### ISSUE TITLE
too many values to unpack(expected 2)

### ISSUE THREAD

**Issue by luckylyw** [mortazavilab/TALON#52]
Hello,

   I used talon_initialize_database,  there's error.

cmd : talon_initialize_database --f Mus_musculus.GRCm38.87.gtf --a gencode.v29 --g hg38 --o example_talon 1>x1.log

Traceback (most recent call last):
  File "/home/luoluo/.local/bin/talon_initialize_database", line 10, in <module>
    sys.exit(main())
  File "/home/luoluo/.local/lib/python3.7/site-packages/talon/initialize_talon_database.py", line 996, in main
    genes, transcripts, exons = read_gtf_file(gtf_file)
  File "/home/luoluo/.local/lib/python3.7/site-packages/talon/initialize_talon_database.py", line 496, in read_gtf_file
    transcript = Transcript.get_transcript_from_gtf(tab_fields)
  File "/home/luoluo/.local/lib/python3.7/site-packages/talon/transcript.py", line 286, in get_transcript_from_gtf
    annotations = extract_transcript_annotations_from_GTF(transcript_info)
  File "/home/luoluo/.local/lib/python3.7/site-packages/talon/transcript.py", line 306, in extract_transcript_annotations_from_GTF
    key, val = pair.split()
ValueError: too many values to unpack (expected 2)

is there something wrong I did???

**Comment by fairliereese** [comment]
We have encountered this error internally and are working on a fix for it. This has to do with extra spaces being present in the last column (the attributes) of the GTF.

**Comment by fairliereese** [comment]
Hi, would you mind doing a fresh git pull from the mod_filtering branch and trying that out? I should have fixed the issue!
