### ISSUE TITLE
Failed to open file talon_tmp/interval_files/1_10554_248944156.bam

### ISSUE THREAD

**Issue by sid-sethi** [mortazavilab/TALON#74]
Hello Talon Team,

I got an error while running the talon annotate step. Could you please help me with this?

Version: v5.0
Command used: talon --f config_file.txt --db talon_gencode_v37_gtf.db --build hg38 --threads 25 --o talon_annotate

Error:

[ 2021-02-23 13:01:09 ] Started TALON run
[E::hts_open_format] Failed to open file talon_tmp/interval_files/1_10554_248944156.bam
[ 2021-02-23 21:16:48 ] Merged input SAM/BAM files
Traceback (most recent call last):
  File "/home/ssethi/.local/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/home/ssethi/.local/lib/python3.7/site-packages/talon/talon.py", line 2429, in main
    read_files = procsams.write_reads_to_file(read_groups, intervals, header_file)
  File "/home/ssethi/.local/lib/python3.7/site-packages/talon/process_sams.py", line 112, in write_reads_to_file
    with pysam.AlignmentFile(fname, "wb", template = template) as f:
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 914, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `talon_tmp/interval_files/1_10554_248944156.bam`: No such file or directory

Many thanks,
Sid

**Comment by slsevilla** [comment]
Checking to see if there was an update to this... I'm also I am wondering why a --tmpDir= flag is not included in the talon command. Not having any control over this dir is problematic when attempting to submit jobs to a HPC where the script dir and output dir are not the same.

**Comment by kopardev** [comment]
PR with a [fix](https://github.com/mortazavilab/TALON/pull/75)
