### ISSUE TITLE
Error with talon_create_GTF

### ISSUE THREAD

**Issue by SziKayLeung** [mortazavilab/TALON#88]
Hello, 

Thank you for creating TALON! It's been really useful, however, I've been getting a final error creating the gtf: 

`talon_create_GTF -db $WKD/mm10_talon.db --whitelist filtered_transcripts.csv -a mm10_annot --build mm10 --o ONTTargeted
Traceback (most recent call last):
  File "/lustre/home/sl693/.conda/envs/sqanti2_py3/bin/talon_create_GTF", line 8, in <module>
    sys.exit(main())
  File "/gpfs/ts0/home/sl693/.conda/envs/sqanti2_py3/lib/python3.7/site-packages/talon/post/create_GTF_from_database.py", line 617, in main
    check_annot_validity(annot, database)
  File "/gpfs/ts0/home/sl693/.conda/envs/sqanti2_py3/lib/python3.7/site-packages/talon/post/create_GTF_from_database.py", line 559, in check_annot_validity
    conn = sqlite3.connect(database)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

It seems to be the error (using the most up-to-date version) with the mm10_talon.db, however, I've been using this for all the upstream processing and it seems to have worked. 

Any guidance on this would be great, thank you! 

Szi Kay

**Comment by SziKayLeung** [comment]
Sorry, just realised I'm missing "-" at the -db. A dumb mistake but easy fix!
